// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmcipsyyhnlquloudalf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tY2lwc3l5aG5scXVsb3VkYWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTYzMjUsImV4cCI6MjA3MDg3MjMyNX0.Y2QM7mf8RHg9jH4WLT2iwU_ggXByGnhPPhO6TkI5tbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});